### ISSUE TITLE
Cannot run examples in the repository - files do not have proper content

### ISSUE THREAD

**Issue by lszl84** [PacktPublishing/CMake-Cookbook#2]
For some of the chapters, the source files do not have proper content, they contain relative paths to other files. As a result the recipes cannot be run.

```
CMake-Cookbook/Chapter08/recipe-04/cxx-example $ cmake -H. -Bbuild       
CMake Error at CMakeLists.txt:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "../../../chapter-04/recipe-03/cxx-example/CMakeLists.txt".


-- Configuring incomplete, errors occurred!
CMake-Cookbook/Chapter08/recipe-04/cxx-example $ cat CMakeLists.txt 
../../../chapter-04/recipe-03/cxx-example/CMakeLists.txt%
CMake-Cookbook/Chapter08/recipe-04/cxx-example $ cat test.cpp 
../../../chapter-04/recipe-03/cxx-example/test.cpp%
CMake-Cookbook/Chapter08/recipe-04/cxx-example $ cat sum_integers.cpp 
../../../chapter-04/recipe-01/cxx-example/sum_integers.cpp%
  
```

**Comment by shlomif** [comment]
@lszl84 : hi! It seems to be an issue in git as well: https://github.com/PacktPublishing/CMake-Cookbook/blob/master/Chapter08/recipe-04/cxx-example/test.cpp . Perhaps these are symbolic links which went bad.

**Comment by TheErk** [comment]
I can confirm that this was a symbolic link at least it is the case in the sibling repo:
https://github.com/dev-cafe/cmake-cookbook.
at least I have no issue with the source from there.

**Comment by shubham763** [comment]
@lszl84 The files are now updated.
